### PR TITLE
Open common location fixes

### LINKED ISSUE #148: Most Common Locations are Greyed Out
Why are the locations mostly greyed out:? 
image

### PR DESCRIPTION
**Pull request by stel**
In sandboxed environment `NSHomeDirectory()` returns path to the app's container directory, not the real user home directory. That's why all found Realm files were displayed in "Other" group of the Open Common Location menu.

This PR also hides empty groups from the menu.

Closes #148.

/cc @TimOliver

### CODE REVIEW

File: RealmBrowser/Application/RLMApplicationDelegate.m [hunk 1]
```diff
@@ -253,6 +253,14 @@ -(void)updateFileItems
 {
     NSString *homeDir = NSHomeDirectory();
     
+    // NSHomeDirectory() returns path to app's container directory like /PATH_TO_HOME_DIRECTORY/Library/Containers/NUNDLE_IDENTIFIER/Data in sandboxed environment.
+    // So removing 4 last path components should give a real path to user's home directory (at least until this path isn't changed).
+    if ([homeDir containsString:[NSBundle mainBundle].bundleIdentifier]) {
+        for (NSInteger i = 0; i < 4; i++) {
+            homeDir = [homeDir stringByDeletingLastPathComponent];
+        }
+    }
```
Comment (bdash) [inline RealmBrowser/Application/RLMApplicationDelegate.m]: You'd be better off using something like `getpwuid(getuid())->pw_dir` to find the real home directory than hard-coding assumptions about the container path.

Comment (stel) [inline RealmBrowser/Application/RLMApplicationDelegate.m]: Yeah, you're right, thanks! It was like a temporary solution actually, but nothing is more persistent than the temporary :) So will make a separate function for this.

**Comment by TimOliver** [comment]
Cool! Looks good to me! Thanks Dmitry! :+1:
